[env]
TERM = "xterm-256color"
[colors.primary]
background = '#0A0E14'
foreground = '#B3B1AD'
[colors.normal]
black = '#01060E'
red = '#EA6C73'
green = '#91B362'
yellow = '#F9AF4F'
blue = '#53BDFA'
magenta = '#FAE994'
cyan = '#90E1C6'
white = '#C7C7C7'
[colors.bright]
black = '#686868'
red = '#F07178'
green = '#C2D94C'
yellow = '#FFB454'
blue = '#59C2FF'
magenta = '#FFEE99'
cyan = '#95E6CB'
white = '#FFFFFF'
[window]
decorations = "none"
startup_mode = "Maximized"
opacity = 0.7
blur = true
option_as_alt = "Both"
[font]
size = 19.5
[font.normal]
family = "JetBrainsMono Nerd Font"
[terminal.shell]
program = "/bin/bash"
args = [
    "-l",
    "-c",
    """
    if command -v tmux >/dev/null 2>&1; then
        if [ -z "$TMUX" ]; then
            tmux attach -t default 2>/dev/null || tmux new -s default
        fi
    fi
    """
]
