alias p='pnpm'
alias px='pnpm dlx'
alias pa='pnpm add --save-prod --save-exact'
alias pad='pnpm add --save-dev --save-exact'
alias nxt='pnpm dlx create-next-app@canary'
alias v='nvim'
alias 4='dig -4 +short myip.opendns.com @resolver1.opendns.com'
alias 6='dig -6 +short TXT o-o.myaddr.l.google.com @ns1.google.com'
alias v.='fd --type f --hidden --exclude .git --exclude .jj | fzf | xargs nvim'
alias ds='podman system prune -a --volumes'
alias db='psql "$( (grep -E "^DATABASE_URL=" .env 2>/dev/null || grep -E "^DATABASE_URL=" .dev.vars 2>/dev/null) | sed -e "s/^DATABASE_URL=//")"'
alias dg='pg_dump "$(grep -E "^DATABASE_URL=" .env | sed -e "s/^DATABASE_URL=//")" --data-only -f seed.sql'
alias cm='git add . && git commit -m'
alias gd='git diff -w --diff-filter=M'
alias nw='mkdir -p'
alias rf='rm -rf'
alias .='cd ..'
alias ..='cd ../..'
alias ...='cd ../../..'
alias ....='cd ../../../..'
alias .....='cd ../../../../..'
alias l='ls -A --color=always'
alias q='cd "$HOME"'
alias d='cd "$HOME/Desktop"'
alias dw='cd "$HOME/Downloads"'
alias z='cd "$HOME/Documents/$(fd --type d --max-depth 1 --base-directory $HOME/Documents | fzf)"'
alias lk='brew update && brew list --formula | xargs brew upgrade && brew list --cask | xargs brew upgrade'
alias kl='brew cleanup && brew cleanup --prune-prefix'
alias spd='sudo wdutil info | awk -F ":" "/Tx Rate/ {gsub(/^[ \t]+/, \"\", \$2); print \$2}"'
alias redis='redis-cli --tls -u'
