alias p='pnpm'
alias px='pnpm dlx'
alias pa='pnpm add --save-prod'
alias pad='pnpm add --save-dev'
alias nxt='pnpm dlx create-next-app@canary'
alias v='nvim'
alias v.='fd --type f --hidden --exclude .git --exclude .jj | fzf | xargs nvim'
alias ds='podman system prune -a --volumes'
alias db='psql "$(grep -E "^DATABASE_URL=" .env | sed -e "s/^DATABASE_URL=//")"'
alias dg='rm ./seed.sql && pg_dump "$(grep -E "^DATABASE_URL=" .env | sed -e "s/^DATABASE_URL=//")" --data-only -f seed.sql && psql "$(grep -E "^DATABASE_URL=" .env | sed -e "s/^DATABASE_URL=//")" -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public; GRANT ALL ON SCHEMA public TO public;"'
alias cln='git clone'
alias ss='git init -b main'
alias cm='git add -N . && git add -p && git commit -m'
alias qcm='git add . && git commit -m'
alias gd='git diff -w --diff-filter=M'
alias gs='git status'
alias psh='git push'
alias pl='git pull'
alias gl='git log'
alias g.='git restore .'
alias nw='mkdir'
alias rf='rm -rf'
alias .='cd ..'
alias ..='cd ../..'
alias ...='cd ../../..'
alias ....='cd ../../../..'
alias .....='cd ../../../../..'
alias l='ls -A --color=always'
alias lt='tree -I "node_modules|.git|.next|raycast|.config/raycast" -a'
alias q='cd "$HOME"'
alias d='cd "$HOME/Desktop"'
alias dw='cd "$HOME/Downloads"'
alias z='cd "$HOME/Documents/$(fd --type d --max-depth 1 --base-directory $HOME/Documents | fzf)"'
alias sl='solana'
alias lk='brew update && brew ls --formulae | xargs brew upgrade --formulae && brew ls --cask | xargs brew upgrade --cask'
alias kl='brew cleanup && brew cleanup --prune-prefix'
alias spd='sudo wdutil info | awk -F ":" "/Tx Rate/ {gsub(/^[ \t]+/, \"\", \$2); print \$2}"'
alias gf='gofmt -w .'
alias redis='redis-cli --tls -u'
alias gob='CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o api'
cl() {
  curl -v "$@" | jq
}
